## Metricbeat configuration
## https://github.com/elastic/beats/blob/main/deploy/docker/metricbeat.docker.yml
#

name: metricbeat

metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
- module: elasticsearch
  hosts: [ https://es01:9200,https://es02:9200,https://es03:9200 ]
  username: elastic
  password: elastic
  xpack.enabled: true
  period: 10s
  enabled: true
  ssl:
    enabled: true
    certificate_authorities: [ "/usr/share/metricbeat/config/certs/elasticsearch-ca.pem" ]
#- module: logstash
#  hosts: [ http://logstash:9600 ]
#  xpack.enabled: true
#  period: 10s
#  enabled: true
- module: kibana
  ssl.enabled: ture
  hosts: [ https://kibana:5601 ]
  username: elastic
  password: elastic
  xpack.enabled: true
  period: 10s
  enabled: true
- module: docker
  metricsets:
    - container
    - cpu
    - diskio
    - healthcheck
    - info
    #- image
    - memory
    - network
  hosts: [ unix:///var/run/docker.sock ]
  period: 10s
  enabled: true

processors:
  - add_cloud_metadata: ~

monitoring:
  enabled: true
  elasticsearch:
    username: elastic
    password: elastic

output.elasticsearch:
  hosts: [  https://es01:9200,https://es02:9200,https://es03:9200 ]
  username: elastic
  password: elastic
  protocol: "https"
  ssl.certificate_authorities: [ "/usr/share/metricbeat/config/certs/elasticsearch-ca.pem" ]


## HTTP endpoint for health checking
## https://www.elastic.co/guide/en/beats/metricbeat/current/http-endpoint.html
#

http:
  enabled: true
  host: 0.0.0.0
